services:
  secvaultwarden:
    image: vaultwarden/server::1.36.0
    container_name: secvaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: https://${VAULTWARDEN_DOMAIN}
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SSO_ENABLED: "true"
      SSO_ONLY: "false"
      SSO_SIGNUPS_ALLOWED: "true"
      SSO_AUTHORITY: ${OIDC_ISSUER}
      SSO_CLIENT_ID: ${VAULTWARDEN_OIDC_CLIENT_ID}
      SSO_CLIENT_SECRET: ${VAULTWARDEN_OIDC_CLIENT_SECRET}
      SSO_SCOPES: "openid email profile"
    volumes:
      - vaultwarden-data:/data
    networks:
      - pangolin_net

volumes:
  vaultwarden-data:

networks:
  pangolin_net:
    external: true
