services:
  secvaultwarden:
    image: vaultwarden/server:1.37.2
    container_name: secvaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: https://${VAULTWARDEN_DOMAIN}
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SSO_ENABLED: "true"
      SSO_ONLY: "false"
      SSO_SIGNUPS_ALLOWED: "true"
      SSO_AUTHORITY: ${OIDC_ISSUER}
      SSO_CLIENT_ID: ${VAULTWARDEN_OIDC_CLIENT_ID}
      SSO_CLIENT_SECRET: ${VAULTWARDEN_OIDC_CLIENT_SECRET}
      SSO_SCOPES: "email profile offline_access"
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: false
      SSO_CLIENT_CACHE_EXPIRATION: 0
      SSO_SIGNUPS_MATCH_EMAIL: true 
    volumes:
      - vaultwarden-data:/data
    networks:
      - pangolin_net

volumes:
  vaultwarden-data:

networks:
  pangolin_net:
    external: true
